# Generated by Django 4.2 on 2023-04-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScaperElement',
            new_name='News',
        ),
    ]
