# Generated by Django 4.2 on 2023-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_news_category_delete_category_delete_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_src',
            field=models.URLField(max_length=255),
        ),
    ]
