# Generated by Django 4.2 on 2023-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_scaperelement_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_src',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
