# Generated by Django 4.2 on 2023-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_news_img_src"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sports", "sports"),
                    ("Video", "video"),
                    ("National", "national"),
                    ("World", "world"),
                    ("Entertainment", "entertainment"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
