# Generated by Django 4.2 on 2023-04-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_news_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
