# Generated by Django 4.2 on 2023-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_news_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoy',
            field=models.CharField(choices=[('sports', 'Sports'), ('video', 'Video'), ('national', 'National'), ('world', 'World'), ('entertainment', 'Entertainment')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
