# Generated by Django 4.2 on 2023-04-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_news_categoy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categoy',
            new_name='category',
        ),
    ]
