# Generated by Django 4.2 on 2023-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_news_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("video", "Video"),
                    ("national", "National"),
                    ("world", "World"),
                    ("entertainment", "Entertainment"),
                ],
                max_length=255,
            ),
        ),
    ]
