# Generated by Django 4.2 on 2023-04-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_site_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="scraper.category",
            ),
            preserve_default=False,
        ),
    ]
