# Generated by Django 4.2 on 2023-04-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_randomclas'),
        ('scraper', '0007_alter_news_category'),
    ]

    operations = [
    ]
